---
version: 2.1

jobs:
  build:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2204:2022.10.2
    steps:
    - checkout
    - restore_cache:
        keys:
        - my_cache
    - run:
        name: Get test data ds114_test1
        command: |
          wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/utils/get_data_from_osf.sh
          bash get_data_from_osf.sh ds114_test1
          bash get_data_from_osf.sh ds114_test2
    - run:
        name: Build Docker image
        command: |
          wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/build_docker.sh
          bash build_docker.sh
        no_output_timeout: 6h
    - save_cache:
        key: my_cache
        paths:
        - ~/docker
        - ~/data
    - persist_to_workspace:
        root: /home/circleci
        paths:
        - data/ds114_test1
        - data/ds114_test2
        - docker/image.tar

  test:
    machine:
      image: ubuntu-2204:2022.10.2
    parameters:
      dataset:
        type: string
      participant:
        type: string
    steps:
    - checkout
    - attach_workspace:
        at: /tmp/workspace
    - run: docker load -i /tmp/workspace/docker/image.tar
    - run: mkdir -p ${HOME}/outputs<< parameters.dataset >>
    - run:
        name: Print version
        command: |
          docker run -ti --rm \
            --user $(id -u):$(id -g) --network=host --env="DISPLAY" --env="HOME" --env="XDG_RUNTIME_DIR" --volume="$HOME:$HOME:rw" --volume="/dev:/dev:ro" --volume="${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}:rw" \
            --volume=/tmp/workspace/data/ds114_test1:/bids_dataset \
            bids/${CIRCLE_PROJECT_REPONAME,,} --version
        no_output_timeout: 1h
    - run:
        name: Run single-subject analysis on << parameters.participant >>
        command: |
          mkdir -p ${HOME}/outputs<< parameters.dataset >>/participant
          docker run -ti --rm \
            --user $(id -u):$(id -g) --network=host --env="DISPLAY" --env="HOME" --env="XDG_RUNTIME_DIR" --volume="$HOME:$HOME:rw" --volume="/dev:/dev:ro" --volume="${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}:rw" \
            --volume=/tmp/workspace/data/ds114_test<< parameters.dataset >>:/bids_dataset \
            --volume=${HOME}/outputs<< parameters.dataset >>/participant:/outputs \
            --volume=${PWD}/tests:/config \
            bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs participant --participant_label << parameters.participant >> \
            --config /config/ds114_test<< parameters.dataset >>.xml,/config/ds114_test<< parameters.dataset >>.m \
            --skip_bids_validator
        no_output_timeout: 6h
    - store_artifacts:
        path: ~/output<< parameters.dataset >>

  deploy:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run: docker load -i /tmp/workspace/docker/image.tar
    - run:
        name: Publish (reprostat)
        command: |
          if [[ -z "${REPROSTAT_TOKEN}" ]]; then
              echo "Docker authentication not detected --> failed"
              exit 1
          else              
              echo ${REPROSTAT_TOKEN} | docker login -u ${REPROSTAT_USER} --password-stdin
              docker tag bids/${CIRCLE_PROJECT_REPONAME} reprostat/${CIRCLE_PROJECT_REPONAME}
              docker tag reprostat/${CIRCLE_PROJECT_REPONAME} reprostat/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}
              docker push --all-tags reprostat/${CIRCLE_PROJECT_REPONAME}
          fi
    #- run:
    #    name: Publish (bids)
    #    command: |
    #      wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/push_docker.sh
    #      bash push_docker.sh

workflows:
  build-test-deploy:
    jobs:
    - build:
        filters:
          tags:
            only: /\d+\.\d+\.\d+/
    - test:
        requires:
        - build
        matrix:
          parameters:
            dataset: ['1', '2']
            participant: ['01', '02']
        filters:
          tags:
            only: /\d+\.\d+\.\d+/
    - deploy:
        context:
        - dockerhub-reprostat
        requires:
        - test
        filters:
          tags:
            only: /\d+\.\d+\.\d+/
          branches:
            ignore: /.*/
